template: |
  # Summary
  @zenvor/hls.js v$INPUT_VERSION - Fork 版本更新

  ## Changes Since The Last Release
  https://github.com/zenvor/hls.js/compare/$PREVIOUS_TAG...v$INPUT_VERSION

  $CHANGES

  ## 安装方式
  ```bash
  npm install @zenvor/hls.js@$INPUT_VERSION
  ```

  ## Feedback
  Please provide feedback via [Issues in GitHub](https://github.com/zenvor/hls.js/issues).

version-template: $COMPLETE
exclude-labels:
  - 'skip-change-log'
